### ISSUE TITLE
CheckpointException JVM: invalid info for restore provided: queued code -1

### ISSUE THREAD

**Issue by hakdogan** [CRaC/openjdk-builds#3]
Hi,

I'm getting jdk.crac.CheckpointException exception when trying create a checkpoint on my simple project.

Since I'm on Mac OS Ventura (M1 architecture) and I cannot run CraC stable in the container I created an Ubuntu instance(Ubuntu Server 22.04 LTS) on Amazon.

Then I took the following steps.

```
wget https://github.com/CRaC/openjdk-builds/releases/download/17-crac%2B5/openjdk-17-crac+5_linux-x64.tar.gz
tar xfv openjdk-17-crac+5_linux-x64.tar.gz
sudo vi ~/.bash_profile
```

Then typed

> export JAVA_HOME="$HOME/openjdk-17-crac+5_linux-x64"
> export PATH=$JAVA_HOME/bin:$PATH

```
source ~/.bash_profile
java -version
openjdk version "17-crac" 2021-09-14
OpenJDK Runtime Environment (build 17-crac+5-19)
OpenJDK 64-Bit Server VM (build 17-crac+5-19, mixed mode, sharing)
```

Then I created manifest.txt file into greetings folder and Greetings.java file into greetings/org/jugistanbul/crac folder.

greetings
|_manifest.txt
|_org
|____jugistanbul
|______________crac
|__________________Greetings.java

Greetings.java

```java
package org.jugistanbul.crac;

public class Greetings 
{
    private static int counter;
    
    public static void main(String[] args) throws InterruptedException {

        while (true){
            System.out.println(String.format("%sth greetings from İstanbul", ++counter));
            Thread.sleep(1000);
        }
    }
}
```

manifest.txt
```
Manifest-Version: 1.0
Main-Class: org.jugistanbul.crac.Greetings
```

Then I execute the following commands separately in greetings folder.

```
javac org/jugistanbul/crac/Greetings.java
jar -cfm greetings.jar manifest.txt org/jugistanbul/crac/Greetings.class
java -jar greetings.jar
```

The output I get is as I expected

> 1th greetings from İstanbul
> 2th greetings from İstanbul
> 3th greetings from İstanbul

Then I run the jar again with -XX:CRaCCheckpointTo parameter as follows
```
java -XX:CRaCCheckpointTo=image -jar greetings.jar
```
And run the following command on another shell window

```
jcmd greetings.jar JDK.checkpoint
```

Result is: 

> May 24, 2023 3:06:42 PM jdk.internal.util.jar.PersistentJarFile beforeCheckpoint
> INFO: /home/ubuntu/greetings/greetings.jar is recorded as always available on restore
> JVM: invalid info for restore provided: queued code -1
> An exception during a checkpoint operation:
> 5th greetings from İstanbul
> jdk.crac.CheckpointException
> 	at java.base/jdk.crac.Core.checkpointRestore1(Core.java:141)
> 	at java.base/jdk.crac.Core.checkpointRestore(Core.java:246)
> 	at java.base/jdk.crac.Core.checkpointRestoreInternal(Core.java:262)
> 6th greetings from İstanbul
> 7th greetings from İstanbul

<img width="1440" alt="Screenshot 2023-05-24 at 18 06 50" src="https://github.com/CRaC/openjdk-builds/assets/657846/a00a6672-3928-4022-91e6-603034693b84">

The image directory contains

```
ls -ls
total 44
 4 -rw-r--r-- 1 ubuntu ubuntu    28 May 24 15:06 cppath
 8 -rw------- 1 ubuntu ubuntu  6653 May 24 15:06 dump4.log
32 -rw------- 1 ubuntu ubuntu 32768 May 24 15:06 perfdata
```

**Comment by rvansa** [comment]
Hi @hakdogan , looks like you did not change the ownership & permissions on `openjdk-17-crac+5_linux-x64/lib/criu` - this needs to be owned by `root` with SUID bit set:

```
sudo chown root:root lib/criu
sudo chmod u+s lib/criu
```

**Comment by rvansa** [comment]
Also mentioned in [the debugging guide](https://github.com/CRaC/docs/blob/master/debugging.md).

**Comment by hakdogan** [comment]
Hi @AntonKozlov,

> I assume that you'll find a few messages about unsufficient permissions there, since in your report:

You're right 

> (00.056443) cg: Dumping cgroups for 1122
> (00.056461) cg:  `- New css ID 1
> (00.056465) cg:     `- [] -> [/user.slice/user-1000.slice/session-1.scope] [0]
> (00.056468) cg: Set 1 is criu one
> (00.056485) Detected cgroup V1 freezer
> (00.056510) Warn  (compel/src/lib/infect.c:127): Unable to interrupt task: 1066 (Operation not permitted)
> (00.056518) Unlock network
> (00.056522) Unfreezing tasks into 1
> (00.056526)     Unseizing 1066 into 1
> (00.056529) Error (compel/src/lib/infect.c:356): Unable to detach from 1066: No such process
> (00.056544) Error (criu/cr-dump.c:2053): Dumping FAILED.

Hi @rvansa thank you for sharing the guide, the example was run fine with the help of both of you.

Thank you.
