### ISSUE TITLE
Can't create checkpoint by docker

### ISSUE THREAD

**Issue by fwborges** [CRaC/openjdk-builds#4]
Hi, I'm trying to create a checkpoint and got no error at command line but on application's log and dump4.log show errors:

Command line message:
`root@fcb2c0b1a9bc:/app# jcmd app.jar JDK.checkpoint
7:
Command executed successfully`

Application's log:
`CR: Checkpoint ...
JVM: invalid info for restore provided (may be failed checkpoint)`

And the dump4.log 

(00.001102) Version: 3.17.1-crac (gitid 8926431+1)
(00.001156) Running on fcb2c0b1a9bc Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64
(00.001168) File /run/criu.kdat does not exist
(00.001182) sockets: Probing sock diag modules
(00.002733) sockets: Done probing
(00.003475) Pagemap is fully functional
(00.003618) Found anon-shmem device at 1
(00.004979) Hugetlb size 2 Mb is supported but cannot get dev's number
(00.005042) Hugetlb size 1024 Mb is supported but cannot get dev's number
(00.005050) Reset 99's dirty tracking
(00.005067)  ... done
(00.005125) Dirty tracking support is OFF
(00.005605) Found task size of 7ffffffff000
(00.032784) Restoring netdev veth idx 10
(00.033637) Dumping netns links
(00.033728)     LD: Got link 1, type 772
(00.033733)     LD: Got link 2, type 768
(00.033735)     LD: Got link 3, type 776
(00.033737)     LD: Got link 10, type 1
(00.034686) vdso: Parsing at 7ffca1fab000 7ffca1fac000
(00.034699) vdso: PT_LOAD p_vaddr: 0
(00.034702) vdso: DT_HASH: 120
(00.034703) vdso: DT_STRTAB: 2d8
(00.034705) vdso: DT_SYMTAB: 1b8
(00.034706) vdso: DT_STRSZ: 72
(00.034707) vdso: DT_SYMENT: 18
(00.034709) vdso: nbucket 3 nchain c bucket 7ffca1fab128 chain 7ffca1fab134
(00.034714) vdso: rt [vdso] 7ffca1fab000-7ffca1fac000 [vvar] 7ffca1fa7000-7ffca1fab000
(00.035244) vdso: Parsing at 7f68df8c9000 7f68df8cb000
(00.035252) vdso: PT_LOAD p_vaddr: 0
(00.035254) vdso: DT_HASH: b4
(00.035256) vdso: DT_STRTAB: 1f0
(00.035257) vdso: DT_SYMTAB: 140
(00.035258) vdso: DT_STRSZ: c0
(00.035259) vdso: DT_SYMENT: 10
(00.035261) vdso: nbucket 3 nchain b bucket 7f68df8c90bc chain 7f68df8c90c8
(00.035263) vdso: compat [vdso] 7ffca1faf000-7ffca1fb1000 [vvar] 7ffca1fab000-7ffca1faf000
(00.035523) cpu: x86_family 6 x86_vendor_id GenuineIntel x86_model_id Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
(00.035531) cpu: fpu: xfeatures_mask 0x5 xsave_size 832 xsave_size_max 832 xsaves_size 832
(00.035540) cpu: fpu: x87 floating point registers     xstate_offsets      0 / 0      xstate_sizes    160 / 160
(00.035543) cpu: fpu: AVX registers                    xstate_offsets    576 / 576    xstate_sizes    256 / 256
(00.036437) Warn  (criu/kerndat.c:1470): CRIU was built without libnftables support
(00.037314) No MOVE_MOUNT_SET_GROUP kernel feature
(00.037508) ptrace(PTRACE_GET_RSEQ_CONFIGURATION) is not supported
(00.037608) Found mmap_min_addr 0x10000
(00.037626) files stat: fs/nr_open 1048576
(00.037628) skip kerndat_save_cache
(00.037641) ========================================
(00.037642) Dumping processes (pid: 7)
(00.037644) ========================================
(00.037650) rlimit: RLIMIT_NOFILE unlimited for self
(00.037655) Running pre-dump scripts
(00.037714) irmap: Searching irmap cache in work dir
(00.037730) No irmap-cache image
(00.037732) irmap: Searching irmap cache in parent
(00.037997) No parent images directory provided
(00.038002) irmap: No irmap cache
(00.038005) cpu: fpu:1 fxsr:1 xsave:1 xsaveopt:1 xsavec:1 xgetbv1:1 xsaves:1
(00.038044) cg-prop: Parsing controller "cpu"
(00.038048) cg-prop:    Strategy "replace"
(00.038052) cg-prop:    Property "cpu.shares"
(00.038054) cg-prop:    Property "cpu.cfs_period_us"
(00.038056) cg-prop:    Property "cpu.cfs_quota_us"
(00.038057) cg-prop:    Property "cpu.rt_period_us"
(00.038058) cg-prop:    Property "cpu.rt_runtime_us"
(00.038059) cg-prop: Parsing controller "memory"
(00.038061) cg-prop:    Strategy "replace"
(00.038062) cg-prop:    Property "memory.limit_in_bytes"
(00.038063) cg-prop:    Property "memory.memsw.limit_in_bytes"
(00.038065) cg-prop:    Property "memory.swappiness"
(00.038066) cg-prop:    Property "memory.soft_limit_in_bytes"
(00.038067) cg-prop:    Property "memory.move_charge_at_immigrate"
(00.038068) cg-prop:    Property "memory.oom_control"
(00.038069) cg-prop:    Property "memory.use_hierarchy"
(00.038071) cg-prop:    Property "memory.kmem.limit_in_bytes"
(00.038072) cg-prop:    Property "memory.kmem.tcp.limit_in_bytes"
(00.038073) cg-prop: Parsing controller "cpuset"
(00.038074) cg-prop:    Strategy "replace"
(00.038076) cg-prop:    Property "cpuset.cpus"
(00.038077) cg-prop:    Property "cpuset.mems"
(00.038083) cg-prop:    Property "cpuset.memory_migrate"
(00.038086) cg-prop:    Property "cpuset.cpu_exclusive"
(00.038087) cg-prop:    Property "cpuset.mem_exclusive"
(00.038089) cg-prop:    Property "cpuset.mem_hardwall"
(00.038090) cg-prop:    Property "cpuset.memory_spread_page"
(00.038091) cg-prop:    Property "cpuset.memory_spread_slab"
(00.038092) cg-prop:    Property "cpuset.sched_load_balance"
(00.038094) cg-prop:    Property "cpuset.sched_relax_domain_level"
(00.038095) cg-prop: Parsing controller "blkio"
(00.038096) cg-prop:    Strategy "replace"
(00.038098) cg-prop:    Property "blkio.weight"
(00.038099) cg-prop: Parsing controller "freezer"
(00.038100) cg-prop:    Strategy "replace"
(00.038102) cg-prop: Parsing controller "perf_event"
(00.038103) cg-prop:    Strategy "replace"
(00.038104) cg-prop: Parsing controller "net_cls"
(00.038106) cg-prop:    Strategy "replace"
(00.038107) cg-prop:    Property "net_cls.classid"
(00.038108) cg-prop: Parsing controller "net_prio"
(00.038110) cg-prop:    Strategy "replace"
(00.038111) cg-prop:    Property "net_prio.ifpriomap"
(00.038112) cg-prop: Parsing controller "pids"
(00.038113) cg-prop:    Strategy "replace"
(00.038114) cg-prop:    Property "pids.max"
(00.038116) cg-prop: Parsing controller "devices"
(00.038117) cg-prop:    Strategy "replace"
(00.038118) cg-prop:    Property "devices.list"
(00.038151) Preparing image inventory (version 1)
(00.038174) Add pid ns 1 pid 99
(00.038284) Add net ns 2 pid 99
(00.038309) Add ipc ns 3 pid 99
(00.038316) Add uts ns 4 pid 99
(00.038320) Add time ns 5 pid 99
(00.038326) Add mnt ns 6 pid 99
(00.038330) Add user ns 7 pid 99
(00.038350) Add cgroup ns 8 pid 99
(00.038355) cg: Dumping cgroups for 99
(00.038373) cg:  `- New css ID 1
(00.038375) cg:     `- [] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038377) cg:     `- [blkio] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038378) cg:     `- [cpu] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038379) cg:     `- [cpuacct] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038381) cg:     `- [cpuset] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038382) cg:     `- [devices] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038383) cg:     `- [freezer] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038384) cg:     `- [hugetlb] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038386) cg:     `- [memory] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038387) cg:     `- [name=systemd] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038388) cg:     `- [net_cls] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038389) cg:     `- [net_prio] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038390) cg:     `- [perf_event] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038392) cg:     `- [pids] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038393) cg:     `- [rdma] -> [/docker/fcb2c0b1a9bc4ee2e6c8c7e61ccd1eecbd60dd58a368463bdd72069f527c4203] [0]
(00.038394) cg: Set 1 is criu one
(00.038404) Detected cgroup V1 freezer
(00.038493) Error (compel/src/lib/ptrace.c:27): suspending seccomp failed: Operation not permitted
(00.038516) Unlock network
(00.038525) Unfreezing tasks into 1
(00.038527)     Unseizing 7 into 1
(00.038529) Error (compel/src/lib/infect.c:356): Unable to detach from 7: No such process
(00.038538) Error (criu/cr-dump.c:2053): Dumping FAILED.

I tried with all releases version and only openjdk-17-crac+3 got no exception on command line and I'm running docker on Win 11 with image docker from maven:3.8.6-eclipse-temurin-11 and install the openJDK manually like tutorial:

Java version:
`root@fcb2c0b1a9bc:/opt/crac-files# java -version
openjdk version "17-crac" 2021-09-14
OpenJDK Runtime Environment (build 17-crac+3-15)
OpenJDK 64-Bit Server VM (build 17-crac+3-15, mixed mode, sharing)`

Tutorial: https://foojay.io/today/how-to-run-a-java-application-with-crac-in-a-docker-container/

Thanks!

**Comment by fwborges** [comment]
Hi again, after create the checkpoint, the restore is stuck.


```
root@29f7cbfedc21:/app# jcmd app.jar JDK.checkpoint
262:
Command executed successfully
root@29f7cbfedc21:/app# ls /opt/crac-files/
core-262.img  core-265.img  core-268.img  core-271.img  core-274.img  core-277.img  core-280.img  core-287.img  core-290.img  core-295.img  core-298.img  core-313.img  core-348.img  cppath        files.img    inventory.img    pages-1.img  seccomp.img   tty-info.img
core-263.img  core-266.img  core-269.img  core-272.img  core-275.img  core-278.img  core-283.img  core-288.img  core-291.img  core-296.img  core-299.img  core-314.img  core-349.img  dump4.log     fs-262.img   mm-262.img       perfdata     stats-dump
core-264.img  core-267.img  core-270.img  core-273.img  core-276.img  core-279.img  core-284.img  core-289.img  core-294.img  core-297.img  core-300.img  core-315.img  core-350.img  fdinfo-2.img  ids-262.img  pagemap-262.img  pstree.img   timens-0.img
``` 

Command to run after create commit on docker container:

```
docker run -it --privileged --rm --name service-name:checkpoint java -jar -XX:CRaCRestoreFrom=/opt/crac-files
``` 

Process on container:
```
root@bcad66502de6:/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   2492   524 pts/0    Ss   01:14   0:00 /opt/jdk/lib/criuengine restorewait
root         9  0.3  2.5 7796640 204560 pts/0  Sl+  01:14   0:07 [java]
root        73  0.0  0.0   4244  3564 pts/1    Ss+  01:15   0:00 /bin/bash
root        92  1.6  0.0   4244  3480 pts/2    Ss   01:49   0:00 /bin/bash
root       102  0.0  0.0   5896  2928 pts/2    R+   01:49   0:00 ps aux
``` 

Thanks!

**Comment by AntonKozlov** [comment]
Hi, thanks for the report. We are also planning to workaround checkpoint issue in the CRaC, the next EA build is expected in a week or two. BTW once you've reverted docker, could you try with the latest EA available (17-crac+5)?

Regarding restore, the ps output does not indicate any problem. I see you're on windows with WSL, right?

Thanks!

**Comment by fwborges** [comment]
Hi @AntonKozlov ! 

I updated to 17-crac+5 with downgrade docker desktop and the checkpoint was succefully.

The ps output was from my container(is other hash because got this log in differents moments but the "error" was the same).

I tried another solution starting java process inside the container instead passing entrypoint.

```
docker run -it --privileged --rm --name service-name:checkpoint

root@f85ef689354f:/app# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.0   4244  3396 pts/0    Ss   12:24   0:00 /bin/bash
root         9  0.0  0.0   5896  2848 pts/0    R+   12:24   0:00 ps aux

root@f85ef689354f:/app# java -XX:CRaCRestoreFrom=/opt/crac-files
pie: 9: Error (criu/pie/restorer.c:1919): Unable to create a thread: -17
pie: 9: Error (criu/pie/restorer.c:2056): Restorer fail 9
Error (criu/cr-restore.c:2593): Restoring FAILED.
``` 

I was looking for restore log but can't found it for more details.

**Comment by fwborges** [comment]
It worked @AntonKozlov !

I'm new to creu and the app started and didn't log anything so I thought it was an error but when I call any endpoint the app returns successfully.

So when I start the app from chekpoint, is it required to display the tomcat log startup or not?

Thank again!

**Comment by AntonKozlov** [comment]
Great! Regarding output, as with regular java program start, when JVM does not print anything on its own, the restored JVM also does not print anything without a need. But the java program can be changed to display some messages.
